language: python

python:
  - "2.7"
  - "3.8"

install:
  - python setup.py install
  - mkdir ~/.taca && cp tests/data/taca_test_cfg.yaml ~/.taca/taca.yaml
  - pip install codecov

script:
  - cd tests && nosetests --with-coverage -v -s

after_success:
  - codecov

notifications:
  email: false
